name: hello.yml 

on: 
    push: 
        branches: 
            - main

jobs:
    hello_world_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Directory content
              run: 
                ls -l
