name: Simple Delpoyment pipeline

on: 
    push: 
      branches: 
          - main
    pull_request: 
      branches: 
        - main
      types: [opened, synchronize]

jobs:
    simple_deployment_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install Dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: Build files
              run: npm run build
            - name: Tests
              run: npm run test
            - name: pseudo Delpoyment
              if: ${{ github.event_name == 'push' }}
              run: echo "Deployment"
    tag_release:
      needs: 
        - simple_deployment_job
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Bump version and  push tag
          if: ${{ github.event_name == 'push' }}
          uses: anothrNick/github-tag-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
    a_test_job:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4
        - name: github context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: commits
          env:
            COMMITS: ${{ toJson(github.event.commits) }}
          run: echo "$COMMITS"
        - name: commit messages
          env:
            COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          run: echo "$COMMIT_MESSAGES"